public class ExceptionTest {
//    public static void main(String[] args) {
//        try {
//            int a = 10 / 0;
//            System.out.println("10/0");
//        }catch (Exception e) {
//            System.out.println("异常为"+e);
//        }finally {
//            int a = 9;
//            System.out.println("a="+a);
//        }
//    }
//public static void main(String[] args) {
//    try{
//        int a = 10 / 0;
//
//    }catch (Exception e){
//        throw e;
//    }
//}
public static void main(String[] args) throws Exception{
    int a = 10 / 0;
    }
}
